package org.boris.pecoff4j;

public class FoundFiles {
    public static final String[] EXE_FILES = {
            "C:\\program files\\Jeskola Buzz\\Tools\\BeanieBuzzMissingMachineManager\\BeanieBuzzMissingMachineManager1.0.exe",
            "C:\\program files\\GnuWin32\\bin\\sync.exe",
            "C:\\program files\\Real Alternative\\Update_OB\\upgrdhlp.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\javaws.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\shift.exe",
            "C:\\program files\\CVSNT\\su.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\java.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\SynZMetr.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\GuidGen.exe",
            "C:\\program files\\Outlook Express\\wabmig.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\pgocvt.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\illusion.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\policytool.exe",
            "C:\\program files\\GnuWin32\\bin\\ls.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gifload.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\rotate.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\tileit.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\guidgen.exe",
            "C:\\program files\\Image-Line\\Downloader\\Uninstall.exe",
            "C:\\program files\\GnuWin32\\bin\\expr.exe",
            "C:\\program files\\GnuWin32\\bin\\false.exe",
            "C:\\program files\\Mozilla Thunderbird\\xpicleanup.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gfig.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_02.b06\\patchjre.exe",
            "C:\\program files\\GnuWin32\\bin\\uptime.exe",
            "C:\\program files\\GnuWin32\\bin\\uname.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\unpack200.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\plasma.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\UddiPublishWizard.exe",
            "C:\\program files\\Jeskola Buzz\\Eaxunified.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jdb.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\winnt\\validatesd.exe",
            "C:\\program files\\Outlook Express\\oemig50.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\pgomgr.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\klist.exe",
            "C:\\program files\\GnuWin32\\bin\\expand.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\apt.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\SqlExpress\\en\\sqlexpr32.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Machine Importer\\gnu\\tar-1.12.msdos.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\checkerboard.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\VJSharpRDP\\vjredist.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\VSA\\8.0\\VsaEnv\\vsmsvr.exe",
            "C:\\program files\\FileZilla Client\\uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\vpropagate.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\Speech\\sapisvr.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\icwrmind.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\javaw.exe",
            "C:\\program files\\GnuWin32\\bin\\dd.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\nmake.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\psd_save.exe",
            "C:\\program files\\Synaptics\\SynTP\\Tutorial.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\whirlpinch.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\midl.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\odbct32w.exe",
            "C:\\program files\\GnuWin32\\bin\\printf.exe",
            "C:\\program files\\InstallShield Installation Information\\{9B5AAC6D-AF21-4034-AF1D-A28274180BA6}\\setup.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\tracefmt.exe",
            "C:\\program files\\Jeskola Buzz\\Buzz.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\pgosweep.exe",
            "C:\\program files\\FileZilla Client\\filezilla.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\dotnetfx\\WindowsInstaller-KB893803-v2-x86.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sample_colorize.exe",
            "C:\\program files\\GnuWin32\\bin\\cut.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\link.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\javaws.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\depthmerge.exe",
            "C:\\program files\\GnuWin32\\bin\\mkfifo.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\csource.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\cvtres.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\extcheck.exe",
            "C:\\program files\\Image-Line\\Collab\\Collab.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\odbcte32.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\video.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\zealouscrop.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\cartoon.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\engrave.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\WiLogUtl.exe",
            "C:\\program files\\CVSNT\\WorkspaceViewer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\cl.exe",
            "C:\\program files\\GnuWin32\\bin\\id.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\tga.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\makecert.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\lib.exe",
            "C:\\program files\\FastStone Image Viewer\\FSViewer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\pvk2pfx.exe",
            "C:\\program files\\GnuWin32\\bin\\chmod.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\raw.exe",
            "C:\\program files\\GnuWin32\\bin\\comm.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Image Editing\\vmount2.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\M2Buzz\\Easyxmid.exe",
            "C:\\program files\\GnuWin32\\bin\\dircolors.exe",
            "C:\\program files\\GnuWin32\\bin\\who.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gradmap.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\klist.exe",
            "C:\\program files\\Real Alternative\\Media Player Classic\\mplayerc.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\orbd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\nmake.exe",
            "C:\\program files\\GnuWin32\\bin\\ginstall.exe",
            "C:\\program files\\Outlook Express\\setup50.exe",
            "C:\\program files\\Mozilla Thunderbird\\updater.exe",
            "C:\\program files\\GnuWin32\\bin\\dirname.exe",
            "C:\\program files\\NetMeeting\\wb32.exe",
            "C:\\program files\\QuickTime\\PictureViewer.exe",
            "C:\\program files\\HTML Help Workshop\\hhc.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\dotnetfx\\dotnetfx.exe",
            "C:\\program files\\Common Files\\InstallShield\\Driver\\11\\Intel 32\\IDriver.exe",
            "C:\\program files\\7-Zip\\Uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\vinvert.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\pgocvt.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\apply_lens.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\ml64.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\fractaltrace.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\spheredesigner.exe",
            "C:\\program files\\Jeskola Buzz\\uMwTool.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\WindowsInstaller3_1\\WindowsInstaller-KB893803-v2-x86.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\rc.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\snoise.exe",
            "C:\\program files\\GnuWin32\\bin\\fmt.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\vcpackages\\vcbuild.exe",
            "C:\\program files\\Jeskola Buzz\\Gear\\Generators\\gentab.exe",
            "C:\\program files\\VMware\\VMware Player\\bin-stats\\vmware-vmx.exe",
            "C:\\program files\\iTunes\\iTunes.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_03.b05\\patchjre.exe",
            "C:\\program files\\GnuWin32\\bin\\df.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pat.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\OverloaderInstaller\\buzzol149E.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\lib.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\ml.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\jusched.exe",
            "C:\\program files\\Internet Explorer\\iexplore.exe",
            "C:\\program files\\Azureus\\Uninstall.exe",
            "C:\\program files\\VMware\\VMware Player\\VMnetDHCP.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\javacpl.exe",
            "C:\\program files\\Outlook Express\\msimn.exe",
            "C:\\program files\\Common Files\\InstallShield\\Driver\\11\\Intel 32\\IDriverT.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\decompose.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\svg.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\sproxy.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jdk1.5.0.b64\\patch-jdk1.5.0_10.b03\\launcher.exe",
            "C:\\program files\\GlobFX Technologies\\Swiff Player\\unins000.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\klist.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\link.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\dumpbin.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\ml64.exe",
            "C:\\program files\\GnuWin32\\bin\\yes.exe",
            "C:\\program files\\MSN\\MSNCoreFiles\\Install\\MSN9Components\\Digcore.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\MSEnv\\VSContentInstaller.exe",
            "C:\\program files\\GIMP-2.0\\bin\\minigzip.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\RowsetViewer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\dotnetfx\\instmsia.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\lib.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\chkrzm.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\pgosweep.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\devenv.exe",
            "C:\\program files\\GnuWin32\\bin\\tty.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\tracepdb.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\grid.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\ml64.exe",
            "C:\\program files\\GnuWin32\\bin\\pathchk.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\InstNT.exe",
            "C:\\program files\\GIMP-2.0\\unins000.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\jucheck.exe",
            "C:\\program files\\VideoLAN\\VLC\\vlc.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\jucheck.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\cvtres.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gfli.exe",
            "C:\\program files\\FileZilla Client\\fzsftp.exe",
            "C:\\program files\\Vim\\vim70\\gvim.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\policytool.exe",
            "C:\\program files\\FastStone Image Viewer\\uninst.exe",
            "C:\\program files\\NetMeeting\\conf.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\compressor.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\CML_explorer.exe",
            "C:\\program files\\Jeskola Buzz\\Gear\\Indexes\\XDiv2d-OL15-8L.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\tnameserv.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jar.exe",
            "C:\\program files\\Common Files\\InstallShield\\Professional\\RunTime\\0701\\Intel32\\DotNetInstaller.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gqbist.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\xdcmake.exe",
            "C:\\program files\\GnuWin32\\bin\\tr.exe",
            "C:\\program files\\AvRack\\rtlrack.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\vcdeploy.exe",
            "C:\\program files\\GnuWin32\\bin\\head.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\java-rmi.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\Xml\\Microsoft.XslDebugProxy.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\jigsaw.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\rc.exe",
            "C:\\program files\\CVSNT\\cvs.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\klist.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\xwd.exe",
            "C:\\program files\\Real Alternative\\settings.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\idlj.exe",
            "C:\\program files\\QuickTime\\qttask.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Samples\\SysMgmt\\Msi\\Patching\\makecab.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\noisify.exe",
            "C:\\program files\\InstallShield Installation Information\\{FB08F381-6533-4108-B7DD-039E11FBC27E}\\Setup.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\odbcte32.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\Remote Debugger\\x86\\mpishim.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\iwarp.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\diffraction.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\tstcon32.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\System\\Tools\\BeatSlicer\\zx_bs_d.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\BuzzFixKit\\buzzfixkit.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\polar.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\rowsetviewer.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\Uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\tiff.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\dumpbin.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\jpeg.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\sgen.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\PatternUtilities\\patutils.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\deinterlace.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\vcredist_x86\\vcredist_x86.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\java.exe",
            "C:\\program files\\QuickTime\\QTSystem\\QuickTimeUpdateHelper.exe",
            "C:\\program files\\GnuWin32\\bin\\date.exe",
            "C:\\program files\\GnuWin32\\bin\\uniq.exe",
            "C:\\program files\\GnuWin32\\bin\\md5sum.exe",
            "C:\\program files\\CVSNT\\extnt.exe",
            "C:\\program files\\Common Files\\InstallShield\\engine\\6\\Intel 32\\IKernel.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_11.b03\\patchjre.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\bmp.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\jusched.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\java.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\colorify.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\scatter_hsv.exe",
            "C:\\program files\\VMware\\VMware Player\\hqtray.exe",
            "C:\\program files\\Synaptics\\SynTP\\SynTPLpr.exe",
            "C:\\program files\\GnuWin32\\bin\\shred.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\pgocvt.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Setup\\VCIntegrate.exe",
            "C:\\program files\\GnuWin32\\bin\\true.exe",
            "C:\\program files\\GnuWin32\\bin\\rm.exe",
            "C:\\program files\\Hurrican\\hurrican.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\vcredist_x64\\vcredist_x64.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\undname.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\mspdbsrv.exe",
            "C:\\program files\\QuickTime\\QTSystem\\ExportController.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\tracewpp.exe",
            "C:\\program files\\IcoFX 1.5\\IcoFX.exe",
            "C:\\program files\\Hurrican\\HurricanStarter.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\jusched.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\vcdeploy.exe",
            "C:\\program files\\Synaptics\\SynTP\\InstNT.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\javacpl.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\unpack200.exe",
            "C:\\program files\\GnuWin32\\bin\\sha1sum.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\Rvsezm.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\pack200.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\mapcolor.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\tiler.exe",
            "C:\\program files\\GnuWin32\\bin\\nl.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\java.exe",
            "C:\\program files\\VMware\\VMware Player\\bin\\vmware-vmx.exe",
            "C:\\program files\\GnuWin32\\bin\\pr.exe",
            "C:\\program files\\GnuWin32\\bin\\mv.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\link.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jconsole.exe",
            "C:\\program files\\GnuWin32\\bin\\gdate.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\java.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\shvlzm.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\glob.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\M2Buzz\\unins000.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_02.b06\\launcher.exe",
            "C:\\program files\\VideoLAN\\VLC\\uninstall.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\rmiregistry.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\M2Buzz\\dirrun.exe",
            "C:\\program files\\Vim\\vim70\\uninstall-gui.exe",
            "C:\\program files\\WinSCP\\PuTTY\\pageant.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\Help 8\\dexplore.exe",
            "C:\\program files\\FLVPlayer\\uninstall.exe",
            "C:\\program files\\Common Files\\InstallShield\\Driver\\11\\Intel 32\\IDriver2.exe",
            "C:\\program files\\Synaptics\\SynTP\\SynTPEnh.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\tile.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\editbin.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\cl.exe",
            "C:\\program files\\Movie Maker\\moviemk.exe",
            "C:\\program files\\GnuWin32\\bin\\whoami.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\rmiregistry.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_11.b03\\launcher.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\ripple.exe",
            "C:\\program files\\VMware\\VMware Player\\vnetsniffer.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\header.exe",
            "C:\\program files\\GnuWin32\\bin\\test.exe",
            "C:\\program files\\Common Files\\GTK\\2.0\\setup\\unins000.exe",
            "C:\\program files\\Image-Line\\Downloader\\ILDownloadManager.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\editbin.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\psp.exe",
            "C:\\program files\\Internet Explorer\\iedw.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\neon.exe",
            "C:\\program files\\Microsoft Virtual PC\\Virtual PC.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\align_layers.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\pktextract.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\MsiCert.exe",
            "C:\\program files\\GnuWin32\\bin\\printenv.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\webbrowser.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pixelize.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\keytool.exe",
            "C:\\program files\\Windows NT\\Accessories\\wordpad.exe",
            "C:\\program files\\wxDownload Fast\\unins000.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\clstencil.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\unpack200.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\rmiregistry.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\VJSharpRDP\\vjsrdpchk.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javac.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\odbct32w.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\ktab.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\AlienMap2.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\icwconn1.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\javaw.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\autocrop.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\animationplay.exe",
            "C:\\program files\\MSDN\\MSDN8.0\\Common\\advtstub.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\javaw.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\cl.exe",
            "C:\\program files\\GnuWin32\\bin\\env.exe",
            "C:\\program files\\MSN\\MSNCoreFiles\\Install\\MSN9Components\\Msncli.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\SqlExpress\\SqlExpressChk.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\PermCalc.exe",
            "C:\\program files\\FLVPlayer\\flvplayer.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\displace.exe",
            "C:\\program files\\InstallShield Installation Information\\{94FB906A-CF42-4128-A509-D353026A607E}\\Setup.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_01.b06\\zipper.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\AtlTraceTool8.exe",
            "C:\\program files\\Windows Media Player\\mplayer2.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jstat.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\consume.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\ReportViewer\\ReportViewerChk.exe",
            "C:\\program files\\MSN\\MSNCoreFiles\\Install\\msnsusii.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gflare.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\servertool.exe",
            "C:\\program files\\7-Zip\\7zFM.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\javacpl.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\laplace.exe",
            "C:\\program files\\Notepad++\\notepad++.exe",
            "C:\\program files\\ConWare\\IconArt\\Reg.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_02.b06\\zipper.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\inetwiz.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_11.b03\\zipper.exe",
            "C:\\program files\\GIMP-2.0\\bin\\gimp-win-remote.exe",
            "C:\\program files\\VMware\\VMware Player\\zip.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Samples\\SysMgmt\\Msi\\Patching\\mpatch.exe",
            "C:\\program files\\VMware\\VMware Player\\vmnetcfg.exe",
            "C:\\program files\\GnuWin32\\bin\\rmdir.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\javaws.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\despeckle.exe",
            "C:\\program files\\Image-Line\\image-line fx\\Uninstall.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\XDCMake.exe",
            "C:\\program files\\GnuWin32\\bin\\sleep.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\rmid.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\javaw.exe",
            "C:\\program files\\GnuWin32\\bin\\echo.exe",
            "C:\\program files\\GnuWin32\\bin\\od.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gimpressionist.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\pvk2pfx.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\normalize.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\film.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Microsoft Visual Studio 2005 Professional Edition - ENU\\setup.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\checkv4.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\java.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\tnameserv.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\ifscompose.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\PEVerify.exe",
            "C:\\program files\\7-Zip\\7zG.exe",
            "C:\\program files\\GnuWin32\\bin\\du.exe",
            "C:\\program files\\GnuWin32\\bin\\tac.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\jusched.exe",
            "C:\\program files\\VMware\\VMware Player\\vmnat.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\randomize.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\ccanalyze.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\link.exe",
            "C:\\program files\\Vim\\vim70\\vim.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\compose.exe",
            "C:\\program files\\Windows NT\\hypertrm.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sunras.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\animoptimize.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\mspdbsrv.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\flarefx.exe",
            "C:\\program files\\CVSNT\\cvsdiag.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\softglow.exe",
            "C:\\program files\\GnuWin32\\bin\\cksum.exe",
            "C:\\program files\\IcoFX 1.5\\unins000.exe",
            "C:\\program files\\GnuWin32\\bin\\cat.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\help.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\mt.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\SynTPEnh.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\oilify.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\unpack200.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\signtool.exe",
            "C:\\program files\\NetMeeting\\cb32.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\Remote Debugger\\x86\\msvsmon.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\odbcte32.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Setup\\Microsoft Visual Studio 2005 Professional Edition - ENU\\setup.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\jucheck.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\keytool.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\javacpl.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\convmatrix.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\M2Buzz\\M2bvc.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\png.exe",
            "C:\\program files\\GnuWin32\\bin\\nice.exe",
            "C:\\program files\\GnuWin32\\bin\\install.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\Buzzync\\BUZZync.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\policytool.exe",
            "C:\\program files\\GnuWin32\\bin\\logname.exe",
            "C:\\program files\\GnuWin32\\bin\\pinky.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jps.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\ltm.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\exchange.exe",
            "C:\\program files\\Real Alternative\\unins000.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\System\\Tools\\FLInstaller\\FLInstaller.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\ResGen.exe",
            "C:\\program files\\CONEXANT\\CNXT_MODEM_PCI_VEN_1039&DEV_7013&SUBSYS_70131039\\HXFSetup.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\HtmlConverter.exe",
            "C:\\program files\\GnuWin32\\bin\\unexpand.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sel2path.exe",
            "C:\\program files\\ConWare\\IconArt\\IconArt.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\Plugins\\Fruity\\Generators\\Chrome\\GraphicsTester.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sinus.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pcx.exe",
            "C:\\program files\\Google\\Google Video Player\\Uninstall.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\ktab.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\plugin-browser.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Machine Importer\\v2vapp.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\vcbuild.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\M2Buzz\\It2xm.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javap.exe",
            "C:\\program files\\Windows Media Player\\setup_wm.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\cubism.exe",
            "C:\\program files\\Foxit Software\\Foxit Reader\\Uninstall.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\orbd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\Remote Debugger\\x64\\mpishim.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\kinit.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\kinit.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jstatd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\bscmake.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\FL.exe",
            "C:\\program files\\ASIO4ALL v2\\uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\nlfilt.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\smooth_palette.exe",
            "C:\\program files\\GnuWin32\\bin\\users.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\dicom.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\blur.exe",
            "C:\\program files\\eMule\\LinkCreator.exe",
            "C:\\program files\\GnuWin32\\bin\\setuidgid.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Samples\\SysMgmt\\Msi\\Patching\\apatch.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\semiflatten.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\bscmake.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\winsnap.exe",
            "C:\\program files\\Vim\\vim70\\install.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\java-rmi.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\rmid.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\rmiregistry.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\policytool.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\cl.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\UddiSdkRegister.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\Tutorial.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\pack200.exe",
            "C:\\program files\\iPod\\bin\\iPodService.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\orbd.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\kinit.exe",
            "C:\\program files\\CVSNT\\cvslock.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\dog.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\servertool.exe",
            "C:\\program files\\GnuWin32\\bin\\kill.exe",
            "C:\\program files\\InstallShield Installation Information\\{E06E4F4E-72D6-4497-BFFD-BCB43077C2F4}\\setup.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\Help\\dexplore.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\wmf.exe",
            "C:\\program files\\Jeskola Buzz\\Spyviewer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\pgomgr.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_01.b06\\patchjre.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\fits.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\mspdbsrv.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\jucheck.exe",
            "C:\\program files\\WinSCP\\WinSCP.exe",
            "C:\\program files\\GnuWin32\\bin\\unlink.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\mt.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\rmiregistry.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\maze.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\rdbgwiz.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\paramfix\\paramfix.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\jucheck.exe",
            "C:\\program files\\PowerISO\\piso.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\policytool.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\winclipboard.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\tnameserv.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\PEVerify.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\javaw.exe",
            "C:\\program files\\Common Files\\GTK\\2.0\\bin\\gspawn-win32-helper-console.exe",
            "C:\\program files\\VMware\\VMware Player\\vmware-acetool.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_10.b03\\launcher.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\Musiccalc.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\flame.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\servertool.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gbr.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\native2ascii.exe",
            "C:\\program files\\Jeskola Buzz\\Gear\\Indexes\\XDi149e.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\glasstile.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\waves.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\keytool.exe",
            "C:\\program files\\Common Files\\GTK\\2.0\\bin\\gspawn-win32-helper.exe",
            "C:\\program files\\Google\\Google Video Player\\GoogleVideoPlayer.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\ktab.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\rmiregistry.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\ASIOControlPanel\\ASIOControlPanel.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\pgosweep.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\keytool.exe",
            "C:\\program files\\VMware\\VMware Player\\vnetstats.exe",
            "C:\\program files\\Azureus\\Azureus.exe",
            "C:\\program files\\GnuWin32\\bin\\gln.exe",
            "C:\\program files\\VMware\\VMware Player\\vmplayer.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sharpen.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\cvtres.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sparkle.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\keytool.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\javaws.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\bckgzm.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\uniteditor.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\TlbExp.exe",
            "C:\\program files\\Windows NT\\dialer.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\graphedt.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\script-fu.exe",
            "C:\\program files\\PowerISO\\PowerISO.exe",
            "C:\\program files\\Microsoft File Transfer Manager\\TransferMgr.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\color_enhance.exe",
            "C:\\program files\\GnuWin32\\bin\\ln.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Setup\\ColReg.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\tnameserv.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\struc.exe",
            "C:\\program files\\InstallShield Installation Information\\{DC226AC9-0314-496C-BE6A-B6A132628466}\\setup.exe",
            "C:\\program files\\GnuWin32\\bin\\stty.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\ktab.exe",
            "C:\\program files\\GnuWin32\\bin\\sum.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\unpack200.exe",
            "C:\\program files\\GnuWin32\\bin\\mkdir.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\UserControlTestContainer.exe",
            "C:\\program files\\GnuWin32\\bin\\gecho.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Microsoft Visual Studio 2005 Professional Edition - ENU\\deletetemp.exe",
            "C:\\program files\\GnuWin32\\bin\\su.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\fp.exe",
            "C:\\program files\\GnuWin32\\bin\\split.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\psd.exe",
            "C:\\program files\\Mozilla Firefox\\plugins\\NPSWF32_FlashUtil.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\servertool.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\helpbrowser.exe",
            "C:\\program files\\Mozilla Firefox\\uninstall\\helper.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\ktab.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\SynTPLpr.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\javaw.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javah.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\Lighting.exe",
            "C:\\program files\\VMware\\VMware Player\\vnetlib.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\signtool.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\SynMood.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pagecurl.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\java-rmi.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jdk1.5.0.b64\\patch-jdk1.5.0_10.b03\\copier.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\klist.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\orbd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\nmake.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\pack200.exe",
            "C:\\program files\\Mozilla Firefox\\xpicleanup.exe",
            "C:\\program files\\GnuWin32\\bin\\tee.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\FractalExplorer.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\spread.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\BuzzScan\\buzzscan.exe",
            "C:\\program files\\GnuWin32\\bin\\hostid.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\MSEnv\\VSLauncher.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\klist.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\tstcon32.exe",
            "C:\\program files\\CVSNT\\genkey.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gee.exe",
            "C:\\program files\\PowerISO\\uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gih.exe",
            "C:\\program files\\GnuWin32\\bin\\fold.exe",
            "C:\\program files\\Vim\\vim70\\vimrun.exe",
            "C:\\program files\\ConWare\\IconArt\\IAExtra.exe",
            "C:\\program files\\iTunes\\iTunesHelper.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\rmic.exe",
            "C:\\program files\\Synaptics\\SynTP\\SynZMetr.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\BuzzIndexer2\\Buzzindexer.exe",
            "C:\\program files\\GnuWin32\\bin\\link.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jdk1.5.0.b64\\patch-jdk1.5.0_10.b03\\patchsdk.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\keytool.exe",
            "C:\\program files\\Image-Line\\Collab\\Uninstall.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\rmid.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\spyxx.exe",
            "C:\\program files\\CVSNT\\postinst.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\javaws.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\undname.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pnm.exe",
            "C:\\program files\\GnuWin32\\bin\\touch.exe",
            "C:\\program files\\Common Files\\GTK\\2.0\\bin\\iconv.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\jucheck.exe",
            "C:\\program files\\Common Files\\GTK\\2.0\\bin\\pango-querymodules.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\lib.exe",
            "C:\\program files\\GnuWin32\\bin\\factor.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\jusched.exe",
            "C:\\program files\\Hurrican\\unins000.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\channel_mixer.exe",
            "C:\\program files\\GnuWin32\\bin\\gsort.exe",
            "C:\\program files\\CVSNT\\cvsservice.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gif.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\hot.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sgi.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\threshold_alpha.exe",
            "C:\\program files\\Mozilla Thunderbird\\uninstall\\helper.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\tnameserv.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\kinit.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\signtool.exe",
            "C:\\program files\\foobar2000\\foobar2000.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\hrtzzm.exe",
            "C:\\program files\\Mozilla Firefox\\updater.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Machine Importer\\exe2cab.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\odbct32w.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\MapObject.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sel_gauss.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\cl.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\uuidgen.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\InstMSI\\instmsiA.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\mosaic.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\serialver.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\servertool.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javaw.exe",
            "C:\\program files\\GnuWin32\\bin\\wc.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\xsd.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\blinds.exe",
            "C:\\program files\\GnuWin32\\bin\\[.exe",
            "C:\\program files\\GnuWin32\\bin\\seq.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\lc.exe",
            "C:\\program files\\Synaptics\\SynTP\\Media\\Setup.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\borderaverage.exe",
            "C:\\program files\\GnuWin32\\bin\\dir.exe",
            "C:\\program files\\Vim\\vim70\\xxd.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\klist.exe",
            "C:\\program files\\VMware\\VMware Player\\vmware-authd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\gacutil.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\tracelog.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\win64\\AMD64\\midlc.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\link.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\tnameserv.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\isignup.exe",
            "C:\\program files\\GnuWin32\\bin\\grmdir.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\pack200.exe",
            "C:\\program files\\MSN Gaming Zone\\Windows\\zClientm.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\policytool.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\rmid.exe",
            "C:\\program files\\wxDownload Fast\\wxDFast.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\VSA\\8.0\\VsaEnv\\mspdbsrv.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_10.b03\\zipper.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\freetype.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\unpack200.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\rmid.exe",
            "C:\\program files\\GnuWin32\\bin\\cp.exe",
            "C:\\program files\\GnuWin32\\bin\\hostname.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\mt.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\servertool.exe",
            "C:\\program files\\Outlook Express\\wab.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\postscript.exe",
            "C:\\program files\\Trillian\\trillian.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\pktextract.exe",
            "C:\\program files\\GnuWin32\\bin\\tail.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\keytool.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\mblur.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\tnameserv.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\warp.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\javaws.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\appletviewer.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\CEL.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\jusched.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\ias.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\kinit.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_03.b05\\launcher.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\sn.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\jureg.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\rmiregistry.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\icwtutor.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javadoc.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\pgocvt.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\ktab.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\AxImp.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\clstencil.exe",
            "C:\\program files\\GnuWin32\\bin\\gmkdir.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\pgomgr.exe",
            "C:\\program files\\Foxit Software\\Foxit Reader\\Foxit Reader.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\lib.exe",
            "C:\\program files\\CVSNT\\chkmanifest.exe",
            "C:\\program files\\Microsoft Virtual PC\\dw15.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\winprint.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\lic.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\winnt\\utl2idl.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\twain.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\ktab.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\Bm2Bm\\bm2bm002.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\winnt\\utl2idl.exe",
            "C:\\program files\\foobar2000\\uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\unsharp.exe",
            "C:\\program files\\GnuWin32\\uninstall\\unins000.exe",
            "C:\\program files\\Internet Explorer\\Connection Wizard\\icwconn2.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\java.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\kinit.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_03.b05\\zipper.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.6.0.b105\\patch-jre1.6.0_01.b06\\launcher.exe",
            "C:\\program files\\GnuWin32\\bin\\stat.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\emboss.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\newsprint.exe",
            "C:\\program files\\VMware\\VMware Player\\bin-debug\\vmware-vmx.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\VJSharpRDP\\dotnetchk.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gee_zoom.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\pix.exe",
            "C:\\program files\\QuickTime\\QTInfo.exe",
            "C:\\program files\\GnuWin32\\bin\\vdir.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\ZipExeStub.exe",
            "C:\\program files\\GnuWin32\\bin\\paste.exe",
            "C:\\program files\\Real Alternative\\mpclauncher.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\wind.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\guillotine.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Machine Importer\\gnu\\gzip.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\procedure-browser.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\sobel.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\consume.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\rmid.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\makehm.exe",
            "C:\\program files\\Image-Line\\FL Studio 7\\Plugins\\Fruity\\Generators\\Chrome\\TunnelProfiler.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jdk1.5.0.b64\\patch-jdk1.5.0_10.b03\\zipper.exe",
            "C:\\program files\\GIMP-2.0\\bin\\gimp-2.2.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\edge.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\max_rgb.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\papertile.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\kinit.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\Remote Debugger\\x64\\msvsmon.exe",
            "C:\\program files\\eMule\\Uninstall.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gauss.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Microsoft Visual Studio 2005 Professional Edition - ENU\\RebootStub.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\x86_amd64\\editbin.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\pgosweep.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\policytool.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\sproxy.exe",
            "C:\\program files\\Common Files\\Java\\Update\\Base Images\\jre1.5.0.b64\\patch-jre1.5.0_10.b03\\patchjre.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\VSA\\8.0\\VsaEnv\\vsaenv.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\InstMSI\\instmsiW.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\servertool.exe",
            "C:\\program files\\Java\\jre1.5.0_11\\bin\\javacpl.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\colortoalpha.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\bumpmap.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\rcm.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\IDE\\MakeZipExe.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\wsdl.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\winnt\\validatesd.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\PlatformSDK\\Bin\\RowsetViewer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Deployment\\regcap.exe",
            "C:\\program files\\GnuWin32\\bin\\mknod.exe",
            "C:\\program files\\WinSCP\\PuTTY\\puttygen.exe",
            "C:\\program files\\GnuWin32\\bin\\chown.exe",
            "C:\\program files\\GnuWin32\\bin\\pwd.exe",
            "C:\\program files\\uTorrent\\uTorrent.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\autostretch_hsv.exe",
            "C:\\program files\\CVSNT\\setci.exe",
            "C:\\program files\\Vim\\vim70\\uninstal.exe",
            "C:\\program files\\GnuWin32\\bin\\chgrp.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\orbd.exe",
            "C:\\program files\\GnuWin32\\bin\\join.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\xpm.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\GuidGen.exe",
            "C:\\program files\\Windows Media Player\\wmplayer.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\ReportViewer\\ReportViewer.exe",
            "C:\\program files\\Mozilla Firefox\\firefox.exe",
            "C:\\program files\\Mozilla Thunderbird\\thunderbird.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\faxg3.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\winnt\\TB3x.exe",
            "C:\\program files\\CVSNT\\cvsagent.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\c_astretch.exe",
            "C:\\program files\\WinSCP\\unins000.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\Buzz2XP\\BuzzWinXP.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\gtm.exe",
            "C:\\program files\\GIMP-2.0\\bin\\bzip2.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\Bin\\TlbImp.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\Bin\\checkv4.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\OverloaderInstaller\\buzzol150M.exe",
            "C:\\program files\\GnuWin32\\bin\\csplit.exe",
            "C:\\program files\\Windows Media Player\\migrate.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\undname.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\jarsigner.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\xbm.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\javaws.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\SDK\\v2.0\\BootStrapper\\Packages\\dotnetfx\\dotnetchk.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\orbd.exe",
            "C:\\program files\\GnuWin32\\bin\\sort.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\imagemap.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\photocopy.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\Common7\\Tools\\errlook.exe",
            "C:\\program files\\Jeskola Buzz\\Patcher.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\pack200.exe",
            "C:\\program files\\GnuWin32\\bin\\ptx.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\unpack200.exe",
            "C:\\program files\\GnuWin32\\bin\\nohup.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\bin\\packager.exe",
            "C:\\program files\\Java\\jre1.5.0_10\\bin\\pack200.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\destripe.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\win64\\x86\\AMD64\\pgomgr.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\curve_bend.exe",
            "C:\\program files\\GnuWin32\\bin\\chroot.exe",
            "C:\\program files\\GnuWin32\\bin\\tsort.exe",
            "C:\\program files\\Vim\\vim70\\diff.exe",
            "C:\\program files\\Messenger\\msmsgs.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\Help 8\\Microsoft Document Explorer 2005\\install.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\amd64\\editbin.exe",
            "C:\\program files\\Jeskola Buzz\\Tools\\ChordsWizard\\ChordWizard.exe",
            "C:\\program files\\Common Files\\VMware\\VMware Virtual Machine Importer\\extract.exe",
            "C:\\program files\\Microsoft Platform SDK for Windows Server 2003 R2\\Bin\\makecert.exe",
            "C:\\program files\\Synaptics\\SynTP\\SynMood.exe",
            "C:\\program files\\Java\\jre1.6.0_02\\bin\\pack200.exe",
            "C:\\program files\\Java\\jre1.6.0_01\\bin\\rmid.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\retinex.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\cvtres.exe",
            "C:\\program files\\Microsoft Virtual PC\\VPCHelper.exe",
            "C:\\program files\\GlobFX Technologies\\Swiff Player\\SWFPlayer.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\jureg.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\winicon.exe",
            "C:\\program files\\Jeskola Buzz\\Gear\\Generators\\DrumKit Manager.exe",
            "C:\\program files\\Notepad++\\uninstall.exe",
            "C:\\program files\\QuickTime\\QuickTimePlayer.exe",
            "C:\\program files\\Java\\jdk1.5.0_10\\jre\\bin\\javacpl.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\MSInfo\\msinfo32.exe",
            "C:\\program files\\GnuWin32\\bin\\basename.exe",
            "C:\\program files\\7-Zip\\7z.exe",
            "C:\\program files\\Microsoft Visual Studio 8\\VC\\bin\\dumpbin.exe",
            "C:\\program files\\Common Files\\Microsoft Shared\\MSEnv\\en\\VSContentInstaller.exe",
            "C:\\program files\\Java\\jre1.6.0_03\\bin\\orbd.exe",
            "C:\\program files\\eMule\\emule.exe",
            "C:\\program files\\GnuWin32\\bin\\readlink.exe",
            "C:\\program files\\GIMP-2.0\\lib\\gimp\\2.0\\plug-ins\\nova.exe" };
}
